export const MOCK_OPPORTUNITIES = [
  {
    id: 1,
    title: 'Community Food Drive',
    organization: 'City Food Bank',
    category: 'Hunger & Food',
    date: 'Oct 15, 2026',
    time: '09:00 AM - 01:00 PM',
    location: 'Downtown Center',
    spots: 8,
    description: 'Help sort, pack, and distribute nutritious food parcels to local families in need.',
    requirements: ['Must be at least 16 years old', 'Comfortable standing for 2-3 hours', 'Friendly and team-oriented attitude'],
  },
  {
    id: 2,
    title: 'Youth Mentorship Program',
    organization: 'Bright Future Foundation',
    category: 'Education',
    date: 'Oct 18, 2026',
    time: '02:00 PM - 05:00 PM',
    location: 'Community Library',
    spots: 4,
    description: 'Mentor middle and high school students with homework assistance and STEM activities.',
    requirements: ['Background check required', 'Basic math or science skills', 'Commitment of 3 hours per session'],
  },
  {
    id: 3,
    title: 'Park Clean-Up & Tree Planting',
    organization: 'Green Earth Initiative',
    category: 'Environment',
    date: 'Oct 22, 2026',
    time: '08:30 AM - 12:30 PM',
    location: 'Riverside Park',
    spots: 12,
    description: 'Join our volunteer team to revitalize park grounds, plant native trees, and clean trails.',
    requirements: ['Wear sturdy closed-toe shoes', 'Bring water bottle and gardening gloves', 'All ages welcome (minors with guardian)'],
  },
  {
    id: 4,
    title: 'Animal Shelter Assistant',
    organization: 'Happy Paws Rescue',
    category: 'Animal Welfare',
    date: 'Oct 25, 2026',
    time: '10:00 AM - 02:00 PM',
    location: 'Westside Shelter',
    spots: 6,
    description: 'Assist with walking dogs, socializing cats, and maintaining clean habitats for shelter animals.',
    requirements: ['Must be 18+ years old', 'Comfortable around animals of all sizes', 'Previous pet care experience preferred'],
  },
  {
    id: 5,
    title: 'Senior Care Companion',
    organization: 'Silver Care Network',
    category: 'Community Support',
    date: 'Nov 02, 2026',
    time: '01:00 PM - 04:00 PM',
    location: 'Sunset Senior Home',
    spots: 5,
    description: 'Spend quality time with elderly residents through reading, board games, and conversation.',
    requirements: ['Patience and empathy', 'Strong communication skills', 'Respectful of community guidelines'],
  },
  {
    id: 6,
    title: 'Tech Literacy Workshop',
    organization: 'Code For All',
    category: 'Education',
    date: 'Nov 05, 2026',
    time: '11:00 AM - 03:00 PM',
    location: 'Downtown Center',
    spots: 10,
    description: 'Guide community members through computer basics, email setup, and online safety.',
    requirements: ['Familiarity with basic computer software', 'Patient and clear teaching approach', 'Bring your laptop if available'],
  },
]
